### ISSUE TITLE
Add streaming version of Marshal

### ISSUE THREAD

**Issue by recht** [capnproto/go-capnproto2#100]
The current Marshal implementation will basically copy all segments into a new byte slice and return that. For some cases it would be nice if there was a Marshal method which took at Writer and wrote to that. Then you can implement stuff like compression and writing to files without having to allocate all data again.

**Comment by zombiezen** [comment]
Have you looked at [`capnp.Encoder`](https://godoc.org/zombiezen.com/go/capnproto2#Encoder)?

**Comment by recht** [comment]
I have. I just completely forgot about it in the meantime, and then I confused myself :)
