### ISSUE TITLE
[question] as a server-only RPC endpoint, is just-1 singleton Foo_ServerToClient() call (thread)"safe" for all subsequent parallel connections?

### ISSUE THREAD

**Issue by metaleap** [capnproto/go-capnproto2#104]
I gather that a `myzomgenpkg.Foo_ServerToClient(myFooImpl)` call needs to happen before doing `NewConn` and `Wait` for each incoming-and-`Accept()`ed "conn" (ie. `ReadWriteCloser`).

**But** --- does it need to happen repeatedly each time we `conn.Accept()`, or can one do it just once prior to the first of infinitely many `conn.Accept()`s?

The *signature* of any given `Foo_ServerToClient` (and a quick glance at its code) of course suggests it's not doing anything related to some "current" transport/connection/request --- it's mostly setting up some `chan`s and collecting all methods and allocating a `func` for each. Overall it *just might* be safe to initialize-once as a singleton and use it all-the-time in parallel as incoming RPC calls are handled with `NewConn` and `Wait`.

But, that doesn't mean *100% sure*. If you say "try and see", OK. But might as well be that there's a clear "yes, they're (or should have been) designed for that" or "nope, not at all designed for that whatsoever" answer straight-away from you dev(s) of this cool package  😁

**Comment by zombiezen** [comment]
A client from `server.New` is designed to receive concurrent calls.  Your code will receive the calls serially, unless you call `server.Ack` (which you likely should if you do any I/O).

However, note that `MainInterface` will close your server unconditionally at the end of the connection, which is likely not safe.  There's definitely some jank there, I'm hoping to address that in the v3 branch (not stable yet, but very soon).  In v3, you would be able to simply add a new reference to your server per connection, and then it would stay alive the entire time.

**Comment by metaleap** [comment]
Thanks for illuminating!  =)  So to summarize, my understanding is, a `server.New` *can safely* chat back and forth with its client connection in parallel (serially-sequenced-or-Ack), *but* at disconnection said "server" object/instance/struct is "closed" (if a `Closer`, I guess?) and thus in any event considered invalid from then onwards?

Use-case at hand (at present) is really just *"every client makes at most one (out of n possible) remote-func invocation and goes away immediately with its results in hand"* --- kinda chunky-rather-than-chatty. That's why I wondered whether I can keep the "server-interface thingy" (possibly even MainInterface call, too) around as a single thing globally (all the "toy sample codes" I saw kinda put server creation together with NewConn-and-Wait) --- because of their construction not taking any current-conn/transport inputs --- but from the above I surmise, better to revisit the question upon v3. Cheers!

**Comment by zombiezen** [comment]
Precisely.  Stay tuned, I have most of Level 0 RPC working in the v3 branch, and Level 1 should come shortly after.
