### ISSUE TITLE
Not so at my end: "Wait will always return an error, usually ErrConnClosed or of type Abort."

### ISSUE THREAD

**Issue by metaleap** [capnproto/go-capnproto2#105]
In fact, I'm having a client running that only checks "server reachability" periodically and hangs up as soon as connected. My fprintdebugging-skillz confirm that my server's `Wait` call in all these cases always returns an `error` of `nil` --- *not* `ErrConnClosed`, also neither an `Abort` nor an `*Abort`.

I do have a `ConnLog` wired up for the server too though (custom little struct implementing `zombiezen.com/go/capnproto2/rpc.Logger`), and it happily prints out `abort: rpc: aborted by remote: rpc: shutdown` (some nesting!) all the while `Wait` returned `nil` at all. (Curiously enough, via `Infof` not `Errorf`.) **So:** there *is* an `Abort` *somewhere* (errors.go being the only place in this repo where the `aborted by remote` message is ever produced) --- just it *isn't* returned by `Wait` (which I'd like and as the docs promise) but *is* logged to the `ConnLog` (which I'd ultimately like to suppress --- hacky string-matching will work I guess :grin: ) 

(Server is accepting clients via `net.Listen("tcp4", ...)` if that matters. Shouldn't of course ;)

**Comment by lthibault** [comment]
Was this an issue on v3?  If not, I'm inclined to close it.

**Comment by zenhack** [comment]
I think this substantially predates v3. I'm going to go ahead and close; if something similar happens, someone can open a new issue.
