### ISSUE TITLE
Convienience wrappers for throwing rpc exceptions

### ISSUE THREAD

**Issue by zenhack** [capnproto/go-capnproto2#106]
For use in some of my own code, I ended up defining this:

https://github.com/zenhack/go.sandstorm/blob/master/internal/errors/errors.go#L27

Which allows for more ergonomically returning the right exception types. Might it make sense to move that (and similar wrappers for the other exception types) into this repository?

**Comment by zombiezen** [comment]
I've addressed this in the v3 branch already: https://github.com/capnproto/go-capnproto2/blob/v3/error.go

I'm still evaluating how much effort I want to put into the existing v2 branch at this point: my plan is to make v2 call into v3, so then there's only one real codebase to maintain.  However, happy to review a pull request for this in the interim.

**Comment by zenhack** [comment]
Quoting Ross Light (2018-02-10 11:23:12)

>    I've addressed this in the v3 branch already:
>    [1]https://github.com/capnproto/go-capnproto2/blob/v3/error.go

Great!

..how much API churn is there on the v3 branch right now? I'm tempted
to start migrating to it now depending. I'll have to at some point since
since some of the issues on the milestone are important to me.

**Comment by zombiezen** [comment]
It's not quite ready to migrate over yet, and I'm trying to minimize churn as much as possible.  Broadly, serialization-only code should largely be unchanged, but RPC code will need to start managing retaining/releasing clients.

The missing RPC wire bits right now are handling promises (#2, but I actually have a strategy this time) and handling tail calls.  However, most tests should pass and work properly.  I'd be happy for you to try it out, if you're okay with a little bit of discomfort. 😃

**Comment by zenhack** [comment]
Happy to guinea pig for you. I'm going to close this, since it already exists on v3.
