### ISSUE TITLE
Decoding into invalid message type

### ISSUE THREAD

**Issue by syhpoon** [capnproto/go-capnproto2#110]
Hey,

I've one question about decoding message into another type.
So let's say I'm serializing message of type `struct X` from the client side using approach from the `Getting started` page:

```go
msg, seg, err := capnp.NewMessage(capnp.SingleSegment(nil))

x, err := protocol.NewRootX(seg)
enc := capnp.NewEncoder(con)
err = enc.Encode(msg)
```

Then on the server side I try to decode it into different type `struct Y`:
```go
dec := capnp.NewDecoder(con)
msg, err := dec.Decode()
y, err := protocol.ReadRootY(msg)
```

And it doesn't return an error! Even though `X` and `Y` have no fields in common.
Is this intentional and (given every type has it's unique ID) is there a way to make sure bytes on the wire actually represent required type?

Thank you.

**Comment by zenhack** [comment]
The type information doesn't exist on the wire, so both ends do need to find another way to agree on the type of the root pointer.

It's worth pointing out that if you're looking to do some kind of rpc with this, capnproto has a standard way to do that. And while there's still no negotiation mechanism built in, you will get an error if you try to call a method on an object that it doesn't support.

If you're desigining the formats yourself you could probably write a wrapper type like:

```capnp
struct TaggedValue {
  typeId @0 :UInt64;
  value @1 :AnyPointer
}
```

And then write some helpers that set the typeId and sanity check it on decode, but no, capnproto doesn't protect you against this by itself.

**Comment by syhpoon** [comment]
Thank you Ian!

**Comment by zenhack** [comment]
You're welcome!
