### ISSUE TITLE
slow message marshalling

### ISSUE THREAD

**Issue by bmartynov** [capnproto/go-capnproto2#111]
Hi @zombiezen, i ran into a problem with message marshalling. 
If struct contains `Text` fields - marshalling took a lot of time.

Info:
Os: Debian buster/sid (testing)
Go: go1.9 linux/amd64

capnp --version
Cap'n Proto version 0.6.1

Schema:
```
using Go = import "/go.capnp";
@0x85d3acc39d94e0f8;
$Go.package("client");
$Go.import("client");

struct Resource {
    schema @0: Text;
    host @1: Text;
    path @2: Text;
}
```

Benchmark:
```
func BenchmarkMarshal(b *testing.B) {
	arena := capnp.SingleSegment(nil)

	msg, seg, err := capnp.NewMessage(arena)
	if err != nil {
		panic(err)
	}

	b.ResetTimer()
	b.ReportAllocs()

	for i := 0; i < b.N; i++ {
		resource, err := NewResource(seg)
		if err != nil {
			b.Fatal(err)
		}

		resource.SetHost("localhost")
		resource.SetSchema("tcp")
		resource.SetPath("some path")

		_, err = msg.Marshal()
		if err != nil {
			b.Fatal(err)
		}
	}
}
```
```
goos: linux
goarch: amd64
pkg: <cut>
30000	    282017 ns/op	  964457 B/op	       2 allocs/op
PASS
```
What i do wrong?

**Comment by zenhack** [comment]
I got this to be about 100 times faster on my machine by moving the arean and mesage creation inside the loop. My guess is what's happening is you're re-using the same message and storage for each pass through the loop, so each successive message is bigger than the last. The message will have gotten quite large by the end of the loop.

**Comment by lthibault** [comment]
Closing as stale.
