### ISSUE TITLE
Examples of initializing lists

### ISSUE THREAD

**Issue by recurser** [capnproto/go-capnproto2#119]
I'm trying to convert an app that uses protocol buffers to Cap'n Proto to do some benchmarking, and I'm having trouble figuring out the best way to initialize a list (a `List(Text)` in this example, but it could be any kind of `List`). Say I have a `Widget`:

```
struct Widget {
  tagList @0 :List(Text);
}
```

... and a list of `tags`:

```
tags := []string{"a", "b", "c"}
```

Is this (skipping error handling for brevity) the recommended way to initialize the `tagList`?

```
_, seg, _ := capnp.NewMessage(capnp.SingleSegment(nil))
widget, _ := mypackage.NewWidget(seg)
numTags := len(tags)
tagList, _ := widget.NewTagList(int32(numTags))
for i := 0; i < numTags; i++ {
  tagList.Set(i, tags[i])
}
```

... or is there a less verbose way to initialize a list with a known set of values? Using protocol buffers it might be `widget.TagList = []string{"a", "b", "c"}`, and the complexity of my solution above makes me wonder if I'm missing something.

I've been digging through the source code but `list_test.go` etc are a bit over my head. There's lots of initializations similar to `val: 0x0000007e00000009` (memory addresses?) but I haven't been able to find any examples initializing with plain lists.

Apologies in advance if I'm missing something obvious - any suggestions would be much appreciated!

**Comment by zenhack** [comment]
Quoting Dave Perrett (2018-06-23 10:55:45)

> Is this (skipping error handling for brevity) the recommended way
> to initialize the tagList?

This is what I've done in the past; I don't think there's a better way
using the normal API. :/. In some cases pogs can be more convenient,
but then you're using reflection and have a marshalling step, so it's
not as appropriate when perf is super important.

>    I've been digging through the source code but list_test.go etc are a
>    bit over my head. There's lots of initializations similar to val:
>    0x0000007e00000009 (memory addresses?) but I haven't been able to find
>    any examples initializing with plain lists.

Memory addresses in a loose sense; Sounds like you're looking at tests
that are checking the code that encodes capnp pointers.

**Comment by recurser** [comment]
Thanks @zenhack - I'll keep doing what I'm doing then :)
