### ISSUE TITLE
no such plugin (executable should be 'capnpc-go')

### ISSUE THREAD

**Issue by wangfeipeng** [capnproto/go-capnproto2#120]
I try to  follow the guide and run the demo  in  internal ,the result is:

$ capnp compile -I$GOPATH/src/zombiezen.com/go/capnproto2/std -ogo *.capnp
go: no such plugin (executable should be 'capnpc-go')
go: plugin failed: exit code 1

I have installed the Cap'n Proto tools. and use the v2.16.0 , I don`t know how to solve  problem ,requst for help , thanks!

**Comment by zombiezen** [comment]
Looks like capnpc-go is not on your `PATH`.  Try running `go install zombiezen.com/go/capnproto2/capnpc-go` and making sure that `$GOPATH/bin` is in your `PATH` environment variable.

**Comment by wangfeipeng** [comment]
@zombiezen  I have runned the go install zombiezen.com/go/capnproto2/capnpc-go , and the 'capnpc-go' is in the $GOPATH/bin
































































































































![image](https://user-images.githubusercontent.com/17864413/42524809-20836a3e-84a4-11e8-86c5-8005db0c79ce.png)

**Comment by zombiezen** [comment]
It sounds like your `PATH` environment variable does not include `$GOPATH/bin`. Try running `echo $PATH` to find out, and if it is not there, then add a line like `export PATH="$GOPATH/bin:$PATH"` to your `~/.bash_profile`.

**Comment by wangfeipeng** [comment]
That did it! Thanks
