### ISSUE TITLE
go.mod: Import path should end with /v2

### ISSUE THREAD

**Issue by thsnr** [capnproto/go-capnproto2#122]
Acording to the Go modules [documentation](https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning), if a module version is v2.x.y, then the import path for that modules should end with /v2, i.e. `zombiezen.com/go/capnproto2/v2`, in order to indicate incompatibility with v1.x.y.

I recognize that go-capnproto2 already solves this problem, since it marks the version incompatibility in the package name itself (`go-capnproto` vs `go-capnproto2`). But I thought I would point out this non-standard behavior.

[Here](https://github.com/golang/go/wiki/Modules#semantic-import-versioning) are some more details on including the major version in the import path.

**Comment by zombiezen** [comment]
Agreed. The main busy work is that I need to set up a shim package that points to the new import path (with type aliases etc) so as not to break existing code. This has been on my radar for a while, but thank you for opening an issue.

**Comment by zenhack** [comment]
How would a shim package like that work? In particular afaik go doesn't have true type aliases, so if you do:

```go
import (
    pkg1 "zombiezen.com/go/capnproto2"
    pkg2 "zombiezen.com/go/capnproto2/v2"
)

func Foo(msg pkg1.Message) {
     ...
}

func Bar(msg pkg2.Message) {
     Foo(msg)
}
```

...the statement in the body of `Bar` won't type check, as there's no way to just re-export Message; the `type` construct creates a new type. What am I missing?

**Comment by zenhack** [comment]
/me remembers search engines exist.

Ah, we do have type aliases! I totally missed when that got added to the language. I have some ideas about other issues then, but sorry for the noise here.

**Comment by zenhack** [comment]
@whisper-bye, it works for me, can you provide more detail?

(also this is probably a separate issue, so this ticket may not be the best place...)

**Comment by whisper-bye** [comment]
@zenhack  thanks for your quick reply, please move to this thread #126

**Comment by zenhack** [comment]
I'm tempted to just close this at this point; the v3 branch does this correctly, and we are mostly not working on the v2 branch at this point (I would accept bug fix patches, but active development is all on v3). It doesn't really seem worth the trouble to shuffle around package paths for versions that are in maintenance mode anyway.

@lthibault, how do you feel about this?

**Comment by lthibault** [comment]
Agreed. Closing.
