### ISSUE TITLE
Allow range based for loop on lists

### ISSUE THREAD

**Issue by worenga** [capnproto/go-capnproto2#127]
Suppose you have a struct like this
```
struct MyStruct {
    message @1 :List(Text);
}
```

When iterating over this list in go is a bit cumbersome at times
```
for i := 0; i < message.Len(); i++ {
   myMsg := message.At(i)
  //...
}
```

Ideally, it would be more convenient to write
```
for _,myMsg := range protectedMsg.Iter() { 
  //...
}
```

**Comment by zombiezen** [comment]
This was an explicit design decision in v2 versus v1: the loop you propose would quietly introduce an allocation, whereas the current approach does not. If you desire more convenient data structures, consider using the [`pogs` package](https://godoc.org/zombiezen.com/go/capnproto2/pogs).
