### ISSUE TITLE
bogus Disembargo messages sometimes sent

### ISSUE THREAD

**Issue by dwrensha** [capnproto/go-capnproto2#128]
Originally reported in https://github.com/capnproto/capnproto-rust/issues/117.

In this simple echo demo, go-capnproto2 sends an erroneous `Disembargo` message: https://github.com/breeswish/capnproto-demo

The messages received by the server before the error is reported are (after hundreds of other unremarkable messages):

```capnp
...
( bootstrap = (questionId = 0) )
( call = (
    questionId = 1,
    target = (
      promisedAnswer = (questionId = 0, transform = []) ),
    interfaceId = 16442975369003573271,
    methodId = 0,
    params = (
      content = <opaque pointer>,
      capTable = [] ),
    sendResultsTo = (caller = void),
    allowThirdPartyTailCall = false ) )
( disembargo = (
    target = (
      promisedAnswer = (questionId = 0, transform = []) ),
    context = (senderLoopback = 0) ) )
```

That `disembargo` does not make sense. `senderLoopback` means that the referred-to promise is known to resolve to a capability hosted by the sender (i.e. the Go client in this case), but the client is not sending any capabilities to the server. The actual thing referred to, the answer to question 0, is the server's bootstrap capability.

**Comment by zombiezen** [comment]
Ack, thanks for the report. There are multiple systemic issues of go-capnproto2's RPC system, and the handling of promised capability resolution is one of the big ones. I'm hoping to fix them with the RPC system rewrite, but that's been stalled on my availability of time to work on it.

**Comment by zenhack** [comment]
I'm going to close this; said rewrite is mostly complete, and so unless and until it can be reproduced on `main` I'm going to assumed this is fixed.
