### ISSUE TITLE
Marshaling/Unmarshaling a list?

### ISSUE THREAD

**Issue by sssilver** [capnproto/go-capnproto2#132]
Struggling to understand how to marshal/unmarshal a capnp list.

Some examples would be neat.

No permutation of the following seems to work:
```go
func MarshalMyList(s mypkg.MyType_List, p []*MyType) error {
	return pogs.Insert(mypkg.MyType_TypeID, s.Struct, p)
}

func UnmarshalMyList(s mypkg.MyType_List) ([]*MyType, error) {
	p := new([]MyType)
	err := pogs.Extract(p, mypkg.MyType_TypeID, s.Struct)
	return p, err
}
```
`s.Struct` demands an integer, and that baffles me.

Any pointers would be much appreciated.

**Comment by sssilver** [comment]
It seems that the proper way to do this is to manually marshal/unmarshal the list:

```go
func MarshalMyList(s mypkg.MyType_List, p []*MyType) error {
	for i := 0; i < s.Len(); i++ {
		err := pogs.Insert(mypkg.MyType_TypeID, s.Struct(i), p)
		if err != nil {
			return err
		}
	}

	return nil
}

func UnmarshalMyList(s mypkg.MyType_List) ([]*MyType, error) {
	p := new(MyType)
	var lp []*MyType

	for i := 0; i < s.Len(); i++ {
		err := pogs.Extract(p, mypkg.MyType_TypeID, s.Struct(i))
		if err != nil {
			return nil, err
		}

		lp = append(lp, p)
	}

	return lp, nil
}
```

Expanding on working with lists in the docs would save some people a lot of time, I imagine.

**Comment by zombiezen** [comment]
Lists should not be serialized as the top-level object. As per the [spec](https://capnproto.org/encoding.html#messages):

> The unit of communication in Cap’n Proto is a “message”. A message is a tree of objects, _with the root always being a struct._ [emphasis mine]

Instead, create a struct type with a single list field and you should be good to go.
