### ISSUE TITLE
Result() not generated for a function that returns a List?

### ISSUE THREAD

**Issue by sssilver** [capnproto/go-capnproto2#133]
The `Result()` function doesn't seem to be generated for a function that returns a `:List(Widget)`.

How is the result supposed to be parsed in the client code?

For functions returning scalar values, I do:
```go
// ...
	retval, err := promise.Result().Struct()
	if err != nil {
		return nil, err
	}
```

But since `Result()` isn't available, it gets a bit confusing.

**Comment by zombiezen** [comment]
A Cap'n Proto interface method that returns a single value will always be silently wrapped with a struct. See the [documentation on generated Interface code](https://godoc.org/zombiezen.com/go/capnproto2#hdr-Interfaces) for more details.

**Comment by zenhack** [comment]
I don't think there's anything actionable here; closing.
