### ISSUE TITLE
Possible race condition when creating RPC connections

### ISSUE THREAD

**Issue by lthibault** [capnproto/go-capnproto2#134]
Hello,

I'm writing a P2P application in which each host opens both a client and server stream to a remote peer.  Here's the code where this happens:

```go
func (s *edgeSpec) newEdge(c context.Context) *Edge {
	cconn := rpc.NewConn(rpc.StreamTransport(s.RPCClientStream))
	client := rpcClient{graph_api.RemoteVertex{Client: cconn.Bootstrap(c)}}

	main := graph_api.RemoteVertex_ServerToClient(rpcServer{s.param})
	sconn := rpc.NewConn(
		rpc.StreamTransport(s.RPCServerStream),
		rpc.MainInterface(main.Client),
	)

        // ...
}
```

Immediately after `newEdge` returns, each peer attempts to call a method of `RemoteVertex`, however, I get a `graph.capnp:RemoteVertex.sample: rpc exception: rpc: target not found` error, followed by `context canceled` on subsequent calls.

Furthermore, this error appears to be stochastic in nature.  Every once in a while, things go as planned, and the calls succeed.

This makes me suspect a race condition in one of the `capnproto2/rpc` functions.  A likely candidate is `rpc.NewConn` given that it starts two goroutines.  Perhaps my RPC method calls are invoked before these are up and running?

I will investigate further, but I would very much appreciate any insights (or corrections if there are mistakes in my code).

**Comment by zombiezen** [comment]
Generally, you should not try to call `rpc.NewConn` multiple times with the same underlying transport, since each assumes exclusive access to the transport. The `sconn` connection you create should be the only one you need: you can still call `sconn.Bootstrap(ctx)` to get the remote peer's bootstrap/main interface.

**Comment by lthibault** [comment]
@zombiezen I'm not sure I follow.  I'm creating two different `rpc.Conn`s with two different underlying transports (each with it's own `net.Conn`).  Have I missed something?

>The sconn connection you create should be the only one you need: you can still call sconn.Bootstrap(ctx) to get the remote peer's bootstrap/main interface.

Just to verify my understanding, each endpoint can call `rpc.NewConn(rpc.StreamTransport(someNetConn), rpc.MainInterface(main.Client))` on the same pipe? If so, that's super cool! 😛

**Comment by zombiezen** [comment]
Your understanding is correct! The Cap'n Proto RPC protocol is full duplex: so there's not really a sense of "server" and "client", just peers. Either side can publish capabilities that the other can use. When you go to create an `rpc.NewConn`, it already starts listening for bootstrap requests.

**Comment by lthibault** [comment]
Absolutely brilliant.  I've never been happier about an invalid issue in my life 😉
Many thanks!

**Comment by lthibault** [comment]
@zombiezen I've made the changes you suggest, but the errors I originally reported still persist.

Any ideas?

Below is the updated function:

```go
func (s *edgeSpec) newEdge(c context.Context) *Edge {
	var e Edge
	var g errgroup.Group

	main := graph_api.RemoteVertex_ServerToClient(rpcServer{s.param})
	conn := rpc.NewConn(rpc.StreamTransport(s.RPCStream), rpc.MainInterface(main.Client))

	e.waitFunc = g.Wait
	e.IDer = s.Remote.Addr()
	e.c, e.cancel = context.WithCancel(log.Set(s.Context(), s.Log()))
	e.GraphSampler = rpcClient{graph_api.RemoteVertex{Client: conn.Bootstrap(c)}}
	e.messageStream = newMessageStream(s.MessageStream, s.param)

	g.Go(e.watchConn(e.messageStream))
	g.Go(e.watchConn(conn))

	return &e
}
```

**Comment by zombiezen** [comment]
Huh, that's odd. Are you perhaps calling this `newEdge` function multiple times? Once you set up your `*rpc.Conn`, you should keep using the same one until you close the connection.

**Comment by lthibault** [comment]
>Huh, that's odd.
I know, right?

>Are you perhaps calling this newEdge function multiple times? 
Nope.  It gets called exactly once per network conn.  Note that sleeping makes the symptom go away (which is why I suspect a data race):

func (s *edgeSpec) newEdge(c context.Context) *Edge {
	var e Edge

	main := graph_api.RemoteVertex_ServerToClient(rpcServer{s.param})
	conn := rpc.NewConn(rpc.StreamTransport(s.RPCStream), rpc.MainInterface(main.Client))

        // ...

	e.GraphSampler = rpcClient{graph_api.RemoteVertex{Client: conn.Bootstrap(c)}}
	
        // ...

        time.Sleep(time.Millisecond)  // <-- this makes the problem disappear
	return &e
}

**Comment by zombiezen** [comment]
Can you try recompiling your program with `go build -race` (without the sleep) and seeing if that triggers any race-condition panics? (This check will not produce a false positive, but may produce false negatives.)

**Comment by lthibault** [comment]
@zombiezen Done.  No race conditions detected.

The plot thickens ... 😉

**Comment by lthibault** [comment]
@zombiezen Ugh, I just realized that the race detector actually makes the symptoms disappear as well... This is shaping up to be quite the Heisenbug.

**Comment by zombiezen** [comment]
It doesn't rule out race conditions, just specifically data races. Thanks for running: it was a bit of a long shot, but would have picked up any easy fixes.

So the error message you included in your initial post only gets triggered when the RPC system detects a protocol violation, specifically that the remote side tries to make a call on a capability descriptor that it never gave out, so my suspicion is still in how your connection is set up, but it absolutely could be a bug in the RPC system.

Could you patch in different error messages into your copy of the `rpc` package to see which case is being triggered? The relevant lines are here:

https://github.com/capnproto/go-capnproto2/blob/e1ae1f982d9908a41db464f02861a850a0880a5a/rpc/rpc.go#L695-L716

**Comment by lthibault** [comment]
@zombiezen I've patched the lines as follows, but _neither_ of them seem to be getting triggered.

```go
func (c *Conn) routeCallMessage(result *answer, mt rpccapnp.MessageTarget, cl *capnp.Call) error {
	switch mt.Which() {
	case rpccapnp.MessageTarget_Which_importedCap:
		id := exportID(mt.ImportedCap())
		e := c.findExport(id)
		if e == nil {
			return errors.New("FOO FOO FOO FOO")
		}
		answer := c.lockedCall(e.client, cl)
		go joinAnswer(result, answer)
	case rpccapnp.MessageTarget_Which_promisedAnswer:
		mpromise, err := mt.PromisedAnswer()
		if err != nil {
			return errors.New("BAR BAR BAR BAR")
		}
```

**Comment by lthibault** [comment]
@zombiezen Apologies, I didn't didn't realize I could scroll down on your snippet.  The error happens on line 716:

```go
pa := c.answers[id]
		if pa == nil {
			return errors.Wrap(errBadTarget, "3")
		}
```

**Comment by lthibault** [comment]
@zombiezen I dug around some more, but I'm [struggling to reproduce the error in a test case](https://gist.github.com/lthibault/705e475bfd4b147926d6fd3b11ec36da).

I thought I'd provide you with a bit more context in the hopes that it helps find the bug.

The code that sets up the `*rpc.Conn`s is here:

https://github.com/lthibault/casm/blob/bc0b52d00d47b50b2a7170a7f7594a1fc6d46452/pkg/graph/internal/edge/edge.go#L118-L136

The above code is invoked when a peer establishes a connection with another peer.  It happens immediately before  `RequestUpgrade` and `Accept Upgrade`, return:

https://github.com/lthibault/casm/blob/bc0b52d00d47b50b2a7170a7f7594a1fc6d46452/pkg/graph/graph.go#L108-L139

The call to `Handle` ultimately triggers a call to `Sample`, which is the failing RPC call.  That happens here:

https://github.com/lthibault/casm/blob/bc0b52d00d47b50b2a7170a7f7594a1fc6d46452/pkg/graph/state.go#L179

The RPC call is implemented here (this is the `rpcClient` and `rpcServer` you saw in `newEdge`):

https://github.com/lthibault/casm/blob/dev/pkg/graph/internal/edge/rpc.go

I don't think I'm using the `*rpc.Conn`  instances any differently than in the gist behind the the first link.  Thoughts?

**Comment by zombiezen** [comment]
Thanks for digging in! I was waiting for some time this last weekend to try to debug more before responding, so thanks for taking the initiative there. I'll step through your code some time this week to try to understand the interactions and advise.

**Comment by lthibault** [comment]
@zombiezen Sounds good, thanks again for your help!  Let me know if any bits of my code need explaining.

**Comment by lthibault** [comment]
@zombiezen Any word on this?  Have you managed to reproduce the bug?

**Comment by zombiezen** [comment]
Thanks for the ping. It's still on my radar, but I haven't had time to reproduce yet.

**Comment by zombiezen** [comment]
Hey @lthibault: I took a look at your code this morning and I'm having a hard time tracing the logic flow across all the packages. Can you create a smaller example that reproduces the issue?

**Comment by lthibault** [comment]
@zombiezen I've been trying to reproduce the issue in a test-case, but I haven't been able to do so. 😕
I've just tried again, but to no avail.

If it helps, I'd be more than happy to hop on a Google Hangout and help you trace the logic flow.  Would you be up for that?

**Comment by lthibault** [comment]
@zombiezen I've finally  managed to resolve this.  The problem was that I had mistakenly assumed the that the context passed to `rpc.Conn.Bootstrap` represented a _bootstrap_ context, i.e. that it provided a mechanism to timeout from the bootstrap protocol.

In reality, it appears that the returned `capnp.Client` remains valid for the duration of the context's lifespan.

I suggest clarifying this in the documentation (and perhaps returning a more useful error than `context cancelled`).

**Comment by zombiezen** [comment]
Hm. I wouldn't have expected that behavior either. I'm going to keep this issue open to make sure it gets fixed for v3.

**Comment by lthibault** [comment]
Great, thanks! To be clear, are you saying the context was intended to define only the bootstrapping lifetime? I.e. does that make this a bug?

**Comment by zombiezen** [comment]
Yes, this is a bug.

**Comment by lthibault** [comment]
I haven't encountered this in a while.  Closing optimistically.
