### ISSUE TITLE
pogs: Panic on invalid composite list

### ISSUE THREAD

**Issue by Oncilla** [capnproto/go-capnproto2#137]
During fuzzing [go-capnproto2](github.com/capnproto/go-capnproto2)  with [go-fuzz](https://github.com/dvyukov/go-fuzz) an error was found when parsing invalid composite lists.
(commit e1ae1f982d9908a41db464f02861a850a0880a5a)

When creating a `capnp.List` from a `capnp.Ptr`, the `uint32` value `Ptr.lenOrCap` is cast to a `int32`, possibly resulting in a negative value. During the validity check, the non-negativity of the list length is not considered, resulting in a panic in the pogs library [extract.go:L261](https://github.com/capnproto/go-capnproto2/blob/e1ae1f982d9908a41db464f02861a850a0880a5a/pogs/extract.go#L261)

A minimal panicking example can be found here: https://github.com/Oncilla/go-capnproto2-fuzz

I'm happy to contribute a fix, but I am unsure what should be fixed here.
Casting vs IsValid check?

**Comment by zombiezen** [comment]
Hi @Oncilla! Thanks for the report. Tracing the code, I suspect the offending line is this one: https://github.com/capnproto/go-capnproto2/blob/e1ae1f982d9908a41db464f02861a850a0880a5a/capn.go#L202

For composite lists, the number of elements is read from the tag word, which is formatted as a struct pointer and can have a negative number. I'd be happy to review a fix.

**Comment by Oncilla** [comment]
@zombiezen I opened a PR to fix this issue and some smaller unpacking bugs (#139)
