### ISSUE TITLE
In-place packed message reader

### ISSUE THREAD

**Issue by asido** [capnproto/go-capnproto2#153]
I wonder is there any reasons why the library unpacks packed messages (`capnp.NewDecoder(in).Decode()`) instead of reading them in-place. [capnproto/capnproto](https://github.com/capnproto/capnproto) provides `capnp::MessageReader` and `capnp::PackedMessageReader`, which from what I know, does it in-place. I could think of getting it done and making a pull request, but before I'd like @zombiezen opinion on this.

**Comment by zombiezen** [comment]
The Cap'n Proto format relies significantly on being able to do random-access reads, so reading from a packed stream directly would have significant performance and complexity concerns.

@kentonv, can you shed some light on what the C++ implementation does with packed messages? Surely it decompresses first and then reads from the decompressed copy?

**Comment by kentonv** [comment]
The C++ implementation unpacks packed messages upfront into buffers allocated on the heap. It doesn't read them in-place. It might lazily unpack each segment on first access (I don't remember).

**Comment by zombiezen** [comment]
Makes sense. I'm going to close out this issue, since I don't think the potential benefits here outweigh the complexity required to do this.
