### ISSUE TITLE
Pass connection context to RPC calls

### ISSUE THREAD

**Issue by pierreis** [capnproto/go-capnproto2#155]
I am trying to make the RPC functionality work with TLS-based client authentication. The implementation is made complicated because there seem to be no version of the server RPC interface that passes the connection context back to the user, from with the peer certificate could be extracted.

Is this functionality part of the roadmap?

**Comment by zombiezen** [comment]
I'm not sure I fully understand what you mean by "connection context" here. Could you pass the information you're looking for into the objects you are constructing as part of setting up the connection with `rpc.NewConn`?

**Comment by pierreis** [comment]
On the server side, when the client calls a method, I would like the method to be able to get the underlying connection. It is different for each client.

This would enable retrieving client-specific information from within the handler, which is not possible at the moment, as no context object is passed to it. Additional information could be accessed by the handler, such as the peer IP address and so forth.

For reference, this is handled in gRPC by including it in the `Context` passed to the handler, and providing a convenience method `peer.FromContext(ctx)` to be able retrieve this information.

**Comment by zombiezen** [comment]
Got it. In general, it's not safe to share server objects between connections, so each one should be able to maintain an identity of which object it belongs to.

**Comment by pierreis** [comment]
There is no shared object between connection.

The request here is merely to pass a context object down to the handler ; i.e. having handlers being `Handle(Context, data)` instead of the current `Handle(data)` in order to enable passing additional context information alongside the data, including the peer IP or TLS certificate if any.

**Comment by zenhack** [comment]
@pierreis, the handlers actually are passed a `Context`, as part of the struct that's passed to the handler, eg:

https://godoc.org/zombiezen.com/go/capnproto2/std/capnp/persistent#Persistent_save

That said, as @zombiezen points out the idiomatic way to do this would be store the client-specific information in the object when it is created during connection setup. e.g:

```go
serverObject := Foo_ServerToClient(&Object{
  connInfo: ...
})
...
``

...and then the RPC methods access the `connInfo` field.
