### ISSUE TITLE
Migrate away from Bazel

### ISSUE THREAD

**Issue by lthibault** [capnproto/go-capnproto2#171]
As discussed in https://github.com/capnproto/go-capnproto2/pull/161#issuecomment-779358734, Bazel builds should be dropped in favor of a suitable alternative.

@zombiezen @zenhack Do you have a high-level path in mind for such a migration?

From my vantage point, it seems like the only intermediate step is generating Go code from templates.  Am I missing anything?

Personally, I'd prefer to use something simple and universal like GNU Make because:

1. It's available everywhere
2. It's installed by default by a lot of toolchains
3. The surprise factor / learning curve is very low

Some of my past projects have used `gomock` for testing, which requires an intermediate code-generation step.  I've had much success with the following `make` target, and I'm wondering if perhaps we could adapt it to our present purposes?

```make
mocks: clean-mocks
# This roundabout call to 'go generate' allows us to:
#  - use modules
#  - prevent grep missing (totally fine) from causing nonzero exit
#  - mirror the pkg/ structure under internal/test/mock
    @find . -name '*.go' | xargs -I{} grep -l '//go:generate' {} | xargs -I{} -P 10 go generate {}
```

This effectively searches through the repo for files beginning with `//go:generate` and passes them into `go generate` with the appropriate flags.

I'm open to other approaches as well, but have a strong personal bias against exotic tools.  Thoughts?

cc @taylorjdawson

**Comment by zenhack** [comment]
Why not just `go generate ./...`?

Do we need an alternative to Bazel or can we just... drop it? I've never used it, the normal go build works just fine afaik.

**Comment by lthibault** [comment]
Fair point.  +1

**Comment by zombiezen** [comment]
I support dropping.
