### ISSUE TITLE
Old import path appears in generated files.

### ISSUE THREAD

**Issue by lthibault** [capnproto/go-capnproto2#176]
Steps to reproduce:

1. Define an arbitrary schema in `foo.capnp`
2. Compile `foo.capnp` using
3. Observe the import lines at the top of `foo.capnp.go`.

```go
import (
	strconv "strconv"
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)
```

I grepped for these lines but couldn't find them anywhere.  @zenhack any ideas?

**Comment by zenhack** [comment]
Can't reproduce; works as expected for me. Are you sure the capnpc-go executable in your path is current? My first guess would be it's an old build from before we changed the paths.

**Comment by lthibault** [comment]
>Are you sure the capnpc-go executable in your path is current?

That was it!  Thanks for the assist.
