### ISSUE TITLE
How to install this? 

### ISSUE THREAD

**Issue by Codebreaker101** [capnproto/go-capnproto2#177]
I followed  instructions mentioned in the [wiki](https://github.com/capnproto/go-capnproto2/wiki/Getting-Started) and got this:

``` bash
$ echo $GOPATH
/home/Codebreaker101/go
$ go get -u zombiezen.com/go/capnproto2/...
$ capnp compile -I$GOPATH/src/zombiezen.com/go/capnproto2/std -ogo foo/books.capnp
capnp compile: -I /home/Codebreaker101/go/src/zombiezen.com/go/capnproto2/std: no such directory
Try 'capnp compile --help' for more information.
$ ls -hal /home/Codebreaker101/go/src/zombiezen.com                                                                                                                                                   
ls: cannot access '/home/Codebreaker101/go/src/zombiezen.com': No such file or directory
```

Seeing how it might be outdated since it was last updated Aug 7, 2016 I went to see [GoDoc](https://pkg.go.dev/capnproto.org/go/capnp/v3#hdr-Generating_code) page where I found instruction and it went as follows:
```
$ go install capnproto.org/go/capnp/v3/capnpc-go
$ capnp compile -I$GOPATH/src/capnproto.org/go/capnp/v3/std -ogo foo/books.capnp
capnp compile: -I /home/Codebreaker101/go/src/capnproto.org/go/capnp/v3/std: no such directory
Try 'capnp compile --help' for more information.
$ ls -hal /home/Codebreaker101/go/src/capnproto.org/
ls: cannot access '/home/Codebreaker101/go/src/capnproto.org/': No such file or directory
```
I tried go install commands inside and outside the project and inside GOPATH. 
```
$ go version
go version go1.16.5 linux/amd64
$ printenv | grep GO
GONOSUMDB=git.<private-repo>/*
GOPATH=/home/Codebreaker101/go
```

**Comment by zenhack** [comment]
Ack, yeah, now that everything's switched over to go modules the paths are different; stuff now gets downloaded into `$GOPATH/pkg/mod/`, and has version qualifiers, so you probably want to do something like

`-I $(go env GOPATH)/pkg/mod/capnproto.org/go/capnp/v3\@v3.0.0-alpha.1/std/`

(with the exact path depending on which version you end up pulling in)
