### ISSUE TITLE
First-time installation

### ISSUE THREAD

**Issue by taufik-rama** [capnproto/go-capnproto2#178]
Hello, I've been trying to to learn about proto serialization. I've been using `protocolbuffers` in my workplace & I want to know about the alternatives.

I have an issue during the installation. When I tried
```bash
$ go get capnproto.org/go/capnp/v3
```
I got an error
```bash
captain@glados:~$ go get capnproto.org/go/capnp/v3
cannot find package "capnproto.org/go/capnp/v3" in any of:
	/usr/local/go/src/capnproto.org/go/capnp/v3 (from $GOROOT)
	/home/captain/go/src/capnproto.org/go/capnp/v3 (from $GOPATH)
```
Same using `GO111MODULE` turned off
```
captain@glados:~$ GO111MODULE=off go get capnproto.org/go/capnp/v3
cannot find package "capnproto.org/go/capnp/v3" in any of:
	/usr/local/go/src/capnproto.org/go/capnp/v3 (from $GOROOT)
	/home/captain/go/src/capnproto.org/go/capnp/v3 (from $GOPATH)
```

My `go env` is
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/captain/.cache/go-build"
GOENV="/home/captain/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/captain/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/captain/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build046804836=/tmp/go-build -gno-record-gcc-switches"
```

Sorry if this seems really basic, just wanted to know if there are other prerequisites/requirements for the installation

**Comment by taufik-rama** [comment]
This might be unrelated, but I also tried using the usual HTTP URL for package installation, similar to other Go's package, but the issue still persist (about the package `"capnproto.org/go/capnp/v3"`)

```bash
captain@glados:~$ go get -x -v -u github.com/capnproto/go-capnproto2
cd /home/captain/go/src/github.com/capnproto/go-capnproto2
git config remote.origin.url
github.com/capnproto/go-capnproto2 (download)
cd /home/captain/go/src/github.com/capnproto/go-capnproto2
git pull --ff-only
cd /home/captain/go/src/github.com/capnproto/go-capnproto2
git submodule update --init --recursive
cd /home/captain/go/src/github.com/capnproto/go-capnproto2
git show-ref
cd /home/captain/go/src/github.com/capnproto/go-capnproto2
git submodule update --init --recursive
code in directory /home/captain/go/src/github.com/capnproto/go-capnproto2 expects import "capnproto.org/go/capnp/v3"
```

**Comment by lthibault** [comment]
@taufik-rama Which version of Go are you using?  Also, can you try `go get capnproto.org/go/capnp/v3` with `GO111MODULE=on` ?

I suspect you may have it (implicitly?) set to `auto`, and be attempting to `go get` from within your gopath, or something similar.  At any rate, you'll need to use modules and you'll need to use `capnproto.org/go/capnp/v3`.

Let us know if the issue persists!

**Comment by taufik-rama** [comment]
Thanks! that seems to be the issue, forgot to try turning it on

Is it okay if I update the `README.md` regarding this? or maybe an FAQ wiki if it exists somewhere

**Comment by lthibault** [comment]
@taufik-rama Yes please!  I think this should go in the "Installation" section.  I'll review the PR ASAP.

Glad we got this working! 😃
