### ISSUE TITLE
Use as capnp.Client to represent :Capability type

### ISSUE THREAD

**Issue by lthibault** [capnproto/go-capnproto2#192]
The built-in type `:Capability` maps onto `capnp.Ptr` in compiled code.  As per [discussion on Matrix](https://matrix.to/#/!pLcnVUHHRZrUPscloW:matrix.org/$z167KlfIznGQaRuUtOFvjFIAsST_ux_ZXP9KHNFjgoQ?via=matrix.org), it would be preferable to represent generic capabilities using `capnp.Client` instead.

@zenhack I have a feeling this one ought to be relatively straightforward.  Assuming this is indeed the case, I'm willing to take a stab at it.  What are the high-level steps involved?

**Comment by zenhack** [comment]
Yeah, it shouldn't be too bad. Have a look at the `anyPointer` field for the `Type` struct in `schema.capnp`, then find the relevant bit in the code generator, and make it actually inspect that for details rather than just doing `capnp.Ptr` for all cases.

**Comment by zenhack** [comment]
Note we might have to do `Interface` instead of `Client`, since the latter isn't necessarily already attached to the message.

**Comment by zenhack** [comment]
#232 is merged; closing.
