### ISSUE TITLE
Provide infallible versions of certain functions.

### ISSUE THREAD

**Issue by zenhack** [capnproto/go-capnproto2#193]
There are many things in the library that can fail if allocation from an underlying arena fails, but in common use never will, because the standard Arena implementations do not ever fail. I don't like throwing out errors, even when I know in principle they should never happen. It would be nice to provide versions of some APIs that choose a fixed arena implementation and take advantage of this to avoid needing an error return. e.g. we could have:

```go
func NewSingleSegmentMessage() (*Message, *Segment) {
        msg, seg, _ := NewMessage(SingleSegment(nil))
        return msg, seg
}
```

I'm not sure how broadly we can do this; it seems like past message creation there may be few places where the caller will be able to specify the arena implementation. But it would be nice to provide these wrappers where applicable.

**Comment by lthibault** [comment]
I'm really glad to see this proposal, especially since I've been wondering for some time exactly when `Arena` allocations could fail.  We may want to document this behavior somewhere.

>I don't like throwing out errors, even when I know in principle they should never happen.

We could also panic instead of throwing away such errors.  That way, an oversight on our part will at least fail noisily.

Relatedly, how feasible would it be to provide infallible versions of accessor methods for data types such as `:Data`, `:Text` etc?  In practice, this results in a lot of `if err != nil` boilerplate, despite the fact that (as far as I can tell) these methods should always succeed if message decoding succeeded.

**Comment by zenhack** [comment]
Quoting Louis Thibault (2021-12-05 13:30:43)

>    I'm really glad to see this proposal, especially since I've been
>    wondering for some time exactly when Arena allocations could fail. We
>    may want to document this behavior somewhere.

It's a function of the implementation of the Arena interface. The implementations
returned by SingleSegment and MultiSegment can fail if you try to
allocate something larger than what fits in a segment, but should never
do so under normal circumstances. But a user provided allocator could in
principle fail for other reasons

>      I don't like throwing out errors, even when I know in principle they
>      should never happen.
> 
>    We could also panic instead of throwing away such errors. That way, an
>    oversight on our part will at least fail noisily.

Good thought.


>    Relatedly, how feasible would it be to provide infallible versions of
>    accessor methods for data types such as :Data, :Text etc? In practice,
>    this results in a lot of if err != nil boilerplate, despite the fact
>    that (as far as I can tell) these methods should always succeed if
>    message decoding succeeded.

The getters can in fact fail for two reasons:

1. Exhausting TraverseLimit or DepthLimit
2. Decoding errors, which happen on field access since we don't do a full
   up front decode.

Particularly for (1), you really should be checking the error.

The setters can fail if allocation fails, and it's hard to know if
that's possible ahead of time since it would require knowing whether
we're using an allocator that can fail.

So it's not obvious to me how to make this better for accessors.

**Comment by zenhack** [comment]
Opened #195 for the NewMessage() variants. We can keep this open for a bit to brainstorm other possibilities.

It seems like we ought to be able to improve on the `NewRoot*` generated methods for cases where you're also creating the message in the same spot.

**Comment by zenhack** [comment]
I'm going to close this; without a specific set of functions it's too open ended to be actionable, but I would be fine adding more if we notice ones that make sense.
