### ISSUE TITLE
my float64 decode returns zero value

### ISSUE THREAD

**Issue by campusstella** [capnproto/go-capnproto2#201]
```
msg, derr := decoder.Decode()
	if derr != nil {
		l.Error().Timestamp().Str("AppLayerDecoder", "NewDecoder.Decode").Msg(derr.Error())
	} else if msg != nil {
		g, _ := ReadRootAppLayerList(msg)
		gl, _ := g.AppLayerList()
		fmt.Println(gl.Len())
		for i := 0; i < gl.Len(); i++ {
			al := gl.At(i)
			spd := baseutils.FixedFloat64(al.AppSpeed(), 4)
			data := bs.SetAppLayer(bs.TimestampLong(al.TimestampLong()), spd)

			out = append(out, data)
		}
	}
```
the AppSpeed() is a float64 value, decoder returns 0.

**Comment by zenhack** [comment]
There's a lot going on here, including calls to packages I'm not familiar with. Could you try to construct an example which:

* Is as simple as possible while still reproducing the problem,
* Includes the capnp schema involved,
* Is a complete program, including import statements and a `main()` function, and
* Avoids other libraries as much as possible.

That will make it much easier to help troubleshoot; as is I'm not even sure what this is supposed to do or what the supposed problem is, and I can't run it.

**Comment by campusstella** [comment]
thank you, the problem caused by my another bug, i found and fixed it yesterday, data ok now.
