### ISSUE TITLE
Reduced memory allocation and copying in Marshall

### ISSUE THREAD

**Issue by flier** [capnproto/go-capnproto2#205]
When we `Marshall` a message, it will [allocate a new buffer and copy all segments](https://github.com/capnproto/go-capnproto2/blob/v3/message.go#L827) to it.

```go
	// Fill buffer.
	buf := make([]byte, int(hdrSize), int(total))
	binary.LittleEndian.PutUint32(buf, uint32(nsegs-1))
	for i := int64(0); i < nsegs; i++ {
		s, err := m.segment(SegmentID(i))
		if err != nil {
			m.mu.Unlock()
			return nil, annotate(err).errorf("marshal")
		}
		if len(s.data)%int(wordSize) != 0 {
			m.mu.Unlock()
			return nil, errorf("marshal: segment %d not word-aligned", i)
		}
		binary.LittleEndian.PutUint32(buf[int(i+1)*4:], uint32(len(s.data)/int(wordSize)))
		buf = append(buf, s.data...)
	}
```
In practice, it is possible to avoid memory allocation and multiple memory copies by allocating a large enough reusable [SingleSegment](https://pkg.go.dev/capnproto.org/go/capnp/v3@v3.0.0-alpha.1#SingleSegment).

```go
var hdrSize = int(streamHeaderSize(0))

type pooledSegmentArena []byte

func (m *Message) Marshal() ([]byte, error) {
	// Compute buffer size.
	nsegs := m.NumSegments()
	if nsegs == 0 {
		return nil, newError("marshal: message has no segments")
	}
	if nsegs == 1 {
		if psa, ok := m.Arena.(*pooledSegmentArena); ok {
			// fast path for single pooled segment
			b := *psa
			binary.LittleEndian.PutUint32(b[4:], uint32(len(m.firstSeg.data)/int(wordSize)))
			return b[:hdrSize+len(m.firstSeg.data)], nil
		}
	}

         // slow path
}
```

We can do this by reserving a headroom (8 bytes?) and fill it in `Marshall`, eliminates the need for any memory allocation and copying on the fast path. We can also reuse this `SingleSegment` through memory pooling to further avoid performance fluctuations caused by garbage collection.

**Comment by zenhack** [comment]
Using an `Encoder` is the intended way to avoid this overhead. I'm not opposed to making Marshal() faster where possible though. Hopefully I'll have time to review the PR soonish, thanks.

**Comment by flier** [comment]
> Using an `Encoder` is the intended way to avoid this overhead. I'm not opposed to making Marshal() faster where possible though. Hopefully I'll have time to review the PR soonish, thanks.

I agree that `Encoder` can reduce memory copies when outputting messages directly to a `Writer`, but it doesn't apply to the  scenario where you need to get a `[]byte` to an external API, such as wrapping into a `Kakfa` message.

In fact I need an `Encoder` or `Marshal` without memory allocation and copying to ensure smooth performance.

Thanks

**Comment by lthibault** [comment]
I've found myself wanting something similar in the past, so I'm very much in favor supporting buffer, arena or message reuse/pooling, provided this is optional (which seems to be the case, here).

I've left a couple of comments on the PR, which looks good overall.  Thanks for submitting this, @flier!

**Comment by lthibault** [comment]
@flier Bump.

**Comment by flier** [comment]
> Reduced memory allocation and copying, #205 #206

Hi @lthibault , sorry I'm late, what else do I need to do, rebase to main?

**Comment by zenhack** [comment]
@flier, yes, per https://github.com/capnproto/go-capnproto2/pull/206#pullrequestreview-847304457

**Comment by lthibault** [comment]
Closing (stale).  @flier Please feel free to re-open this issue an create a new PR if you would like to pursue this 🙂
