### ISSUE TITLE
Capabilities received as arguments are implicitly released when RPC handler returns.

### ISSUE THREAD

**Issue by lthibault** [capnproto/go-capnproto2#218]
I encountered some surprising behavior in an RPC handler today.  Essentially:

```go
type fooer struct{}

func (fooer) Foo(ctx context.Context, call foo.Foo_foo) error {
    cap := call.Args().SomeCapability()
    go func() {
        f, release := cap.MyMethod(ctx, nil)
        defer release()

       if  _, err := f.Struct(); err != nil {
           panic(err)  // XXX:  "capnp: call on released client"
       }
    }()
}
```

It appears that all capabilities contained in `call.Args()` are implicitly freed when `Foo` returns ([source](https://github.com/capnproto/go-capnproto2/blob/main/server/server.go#L265)) in a call to [`ReleaseArgs`](https://github.com/capnproto/go-capnproto2/blob/main/capability.go#L753-L755).  The implementation of `ReleaseArgs` appears to be in [`handleCall`](https://github.com/capnproto/go-capnproto2/blob/main/rpc/rpc.go#L604-L611).

Looking at `ReleaseArgs`, the docstring does not match the actual behavior.  Arguments are _always_ released when an RPC handler returns, even if a reference to the args struct is still held.

In my example, the behavior _technically_ matches the spec, since I do not hold a reference to `call.Args()` beyond `Foo`'s call frame.  Nevertheless, this behavior is quite surprising, and it is not documented in a place where the user is likely to see it. 

I see three possible approaches:

1. Update the docstring to reflect reality *and* document this behavior in a place where the user is likely to see it.
2. Don't release capabilities in `ReleaseArgs`, and instead rely on the (existing!) calls to `runtime.SetFinalizer` to release clients when they are garbage-collected.
3. Add a manual `Finish()` method to `call`, which frees all resources.

If I'm reading the source code correctly, any structs read from arguments will remain valid after a call to `ReleaseArgs`.  My reasoning is as follows:

1. `ReleaseArgs` ultimately calls `releaseCall` in `handleCall`.
2. The above `releaseCall` is exactly the `capnp.ReleaseFunc` returned by a call to `Transport.RecvMessage`.
3. The above `capnp.ReleaseFunc` simply calls `capnp.Message.Reset(nil)`
4. As per the `Reset` docstring, pointers are invalidated in the _message_, but the prevous _arena_, and the messages it contiains, remains unaffected.

Assuming I haven't missed anything important, option 2 seems like it should be preferred.  @zenhack, thoughts?

**Comment by zenhack** [comment]
What happens if you do:

```
    cap := call.Args().SomeCapability().AddRef()
    // ...
```

?

**Comment by lthibault** [comment]
Oh sorry, I forgot to mention that bit.  `AddRef()` solves the immediate problem.  However, if I subsequently call `Release()`, it blocks indefinitely.  Currently investigating this.

**Comment by zenhack** [comment]
That *does* sound like a bug to me; let me know if you find anything.

**Comment by lthibault** [comment]
I'm beginning to suspect this is a race condition, as the problem disappears with a minor change to the ordering of a `context.CancelFunc` call and a `Client.Release()` call.  So long as `Client.Release` is not called concurrently, this _seems_ to work.  I'll continue to investigate.

As a matter of API design, I feel like `Client.Release()` should be idempotent and thread-safe.  Is there a particular reason why it is not?

**Comment by zenhack** [comment]
Quoting Louis Thibault (2022-01-16 16:58:57)

>    As a matter of API design, I feel like Client.Release() should be
>    idempotent and thread-safe. Is there a particular reason why it is not?

I think that makes sense. But skimming the implementation it looks like
it already should be. Can you publish a minimal example showing the
race?

**Comment by lthibault** [comment]
>But skimming the implementation it looks like it already should be.

Going by the docstring, it seems like it should panic if called repeatedly.

```go
// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c *Client) Release()
```

On closer inspection, though, it seems like the assigning of `c.h = nil` prevents this from happening?  Hopefully we just need to clarify the docstring 🙂 

>Can you publish a minimal example showing the race?

I'm currently trying to reproduce it outside of the application code.  I'll post a test case if I manage to isolate it (or, conversely, let you know if it turns out to be an application-level bug).

**Comment by lthibault** [comment]
I'm fairly convinced this was a false-alarm.  Closing.
