### ISSUE TITLE
Build fails on 32 bit

### ISSUE THREAD

**Issue by haircommander** [capnproto/go-capnproto2#236]
Hey folks! 

We're hitting issues compiling on 32 bit machines. we get this error `vendor/capnproto.org/go/capnp/v3/message.go:753:14: cannot convert maxSegmentSize (constant 4294967288 of type Size) to type int` when building on a i386 machine (the run is [here](https://github.com/cri-o/cri-o/runs/6297167833?check_suite_focus=true) )

Is there any intention to build for 32 bit? if not, is there any way support for it could be spoofed out so we can compile at least?

we're using 3.0.0-alpha.1 btw (our linter doesn't support generics well yet so we've not yet upgraded to alpha.2)

Thanks!

**Comment by lthibault** [comment]
Hi @haircommander have you tried running from the latest tip of `main`?  We just merged a PR addressing 32-bit builds yesterday.

Either way, we do intend for 32-bit builds to work, so definitely follow-up with us if it keeps failing.  We'll get you sorted ASAP.

**Comment by haircommander** [comment]
ahh I see. the migration to generics made our linters sad (not the fault of go-capnp, but a migration woe nonetheless). I will give it a shot, thanks for the timely response :smile:

**Comment by zenhack** [comment]
Going to close, since this is fixed on main.
