### ISSUE TITLE
Move `internal/packed` out of `internal`

### ISSUE THREAD

**Issue by zenhack** [capnproto/go-capnproto2#256]
I recently ran into a use case where I wanted to using packed encoding on just a bare segment -- with no message header. The exposed interfaces in the main package don't provide a way to do this, and the raw Pack()/Unpack() apis in the packed package are under internal. I think we should move that package out of internal; there's no reason I see why this should be private.

**Comment by lthibault** [comment]
Oh good!  I ran into a similar case a while back (I wanted to reuse `[]byte` buffers ... can't remember the details), and this has been in the back of my mind ever since.  +1 from me.
