### ISSUE TITLE
Wiki Update Patch

### ISSUE THREAD

**Issue by mxplusb** [capnproto/go-capnproto2#267]
I wrote a patch for the wiki update, but I can't fork the wiki or open a PR for it, so I'm submitting a link to the patch for review here.

https://gist.github.com/mxplusb/b8b294ac281d02096781bfa5740052ce

**Comment by zenhack** [comment]
Pushed, thanks! I think you should be able to just *edit* the wiki, though not push to it from the cli.

**Comment by mxplusb** [comment]
Ahhhh that's what I missed, thank you though!
