### ISSUE TITLE
Fix issues flagged by goreportcard

### ISSUE THREAD

**Issue by lthibault** [capnproto/go-capnproto2#280]
I just had a look at our [Go Report Card](https://goreportcard.com/report/capnproto.org/go/capnp/v3) and noticed a handful of code-quality issues that should be quick to fix.  I am creating this issue to track them, and will submit a PR shortly.

### Checklist

- [x] `pointer_test.go`, line 1:  file not gofmted with `-s`
- [x] `Ineffassign` of `err` in `rpc/rpc.go`
  - [x] Line 1372
  - [x] Line 1378
  - [x] Line 1391
- [x] Misspellings
  - [x] `internal/mpsc/mpsc_test.go`:  Lines 69 & 114:  s/Recieved/Received
  - [x] `message.go`:  Line 113:  s/Analagous/Analogous
  - [x] `rpc/export.go`:  Line 191:  s/capabiltiy/capability
  - [x] `rpc/rpc.go`
    - [x] Line 1160 & 1164:  s/capabiltiy/capability 
    - [x] Line 1211:  s/becasue/because
    - [x] Line 1222: s/embargos/embargoes

**Comment by zenhack** [comment]
Is there some way we can integrate this into CI (maybe by integrating the underlying linters)?

Also, I noticed that the badge in the README isn't a link to the report card, it's a link to... the image of the badge...

**Comment by lthibault** [comment]
>Is there some way we can integrate this into CI (maybe by integrating the underlying linters)?

Not sure offhand, but agree this would be helpful.

>Also, I noticed that the badge in the README isn't a link to the report card, it's a link to... the image of the badge...

I noticed this as well, but I think the image is dynamically updated based on the state of the report card.  I'll double-check.

**Comment by lthibault** [comment]
Badge in README is fixed.
