### ISSUE TITLE
Handle errors returned from `Conn.sendMessage`

### ISSUE THREAD

**Issue by lthibault** [capnproto/go-capnproto2#304]
While investigating #303, @zenhack and I observed that most calls to `Conn.sendMessage` were ignoring the returned error.  The immediately problematic call sites have been fixed, but we'll want to respond to those other errors as well.  At a minimum, we might consider passing them to `ErrorReporter`, or terminating the connection.

@zenhack suggested it might be possible to detect this issue using a custom linter.

**Comment by zenhack** [comment]
Quoting Louis Thibault (2022-09-20 11:03:39)

> @zenhack suggested it might be possible to detect this issue using a
> custom linter.

I strongly suspect there's an off-the-shelf one that does what we need.
