### ISSUE TITLE
Generated code does not compile when a field is named "message" or "segment"

### ISSUE THREAD

**Issue by mologie** [capnproto/go-capnproto2#419]
After upgrading from alpha.1 to alpha.19 I receive the following new error when compiling generated schema code:
```
test/example.capnp.go:1607:23: Foo.Message redeclared in this block
	test/example.capnp.go:1592:23: other declaration of Message
```

Minimal example to reproduce:
```sh
#!/bin/sh

mkdir nameclash
cd nameclash

cat <<"EOF" >nameclash.capnp
@0x97aa969ec333a351;

using Go = import "go.capnp";

$Go.package("nameclash");
$Go.import("nameclash");

struct Foo {
  message @0 :Text;
  segment @1 :Text;
}
EOF

cat <<"EOF" >capnpc-go
#!/bin/sh
exec go run capnproto.org/go/capnp/v3/capnpc-go "$@"
EOF
chmod +x capnpc-go
export PATH=$(pwd):$PATH

go mod init nameclash
go get capnproto.org/go/capnp/v3@v3.0.0-alpha.19
curl -sL https://raw.githubusercontent.com/capnproto/go-capnproto2/v3.0.0-alpha.19/std/go.capnp -o go.capnp

capnp compile -ogo nameclash.capnp
go build .
```

Expected behavior: No error from `go build`.

Actual output:

```
$ go build .
# nameclash
./nameclash.capnp.go:58:14: Foo.Message redeclared in this block
	./nameclash.capnp.go:51:14: other declaration of Message
./nameclash.capnp.go:76:14: Foo.Segment redeclared in this block
	./nameclash.capnp.go:55:14: other declaration of Segment
```

<hr/>

The field "message" appears 8 times in separate places in my code. I'd prefer to avoid changing those all, and rather help improve the library by resolving the name clash.

It appears that names previously taken in alpha.1, such as `Size()`, were made available again in some version before alpha.19. They now require an explicit cast to `capnp.Struct`. I assume this was intentional to avoid such exact clashes, and I really like the simplicity of the mechanism.

Could we drop the .Message() and .Segment() wrappers on generated code too, so that an explicit cast is required to access library-internal functions and thus avoid a clash with user-defined field names?

**I can open a PR for this if it's OK with you, plus fix up existing usages within this repo.** This change would be backwards-incompatible. 

Best,

Oliver

**Comment by lthibault** [comment]
Hi Oliver, thanks for reporting the issue!  I'm surprised this ever worked, as the `.Message()` method exists in the alpha.1 release as well.  Is it possible that something else changed?

>Could we drop the .Message() and .Segment() wrappers on generated code too, so that an explicit cast is required to access library-internal functions and thus avoid a clash with user-defined field names?

I'm hesitant to make this change since it's likely to break a larger number of builds (assuming this indeed worked in alpha.1 - I haven't had time to check, yet).  @zenhack ?

Hopefully we'll have a stable API soon-ish, and this kind of nuisance will go away. 😃

**Comment by lthibault** [comment]
Thanks, Oliver!  I'm on mobile right now, so this is super helpful.

>I suppose that they instead were available implicitly when Go expanded the inlined capnp.Struct definition.

Ah yes, that makes sense.

Let's wait for zenhack's input on this, but to be honest, my inclination is to leave this as-is.  I understand where you're coming from (and I'm glad you suggested the fix!), but my main concern is that `.Message()` is an important part of the API, and requiring an explicit cast makes it less discoverable.  Moreover, the proposed change is likely to break a larger number of builds.

As much as I hate to play the "alpha card", well... alpha software... 😕

**Comment by mologie** [comment]
Alright, thank you for looking into this so far either way Louis, I really appreciate it!

I did not consider the Message and Segment generated methods to be important so far, since there were no references to Message() in this repo (tests still run through with it removed), and only generated code for interface setters referenced Segment(), where a cast would be harmless.

So until I can call my fields "message" I'll just throw this sed-style Uno reverse card right on top of your alpha card. Beats changing schema files until a more permanent solution is available. 🙈 

`exec sed -E -i '' -e "s/(Message|Segment)\(\) \*capnp/\1_() *capnp/;s/s\.Segment\(\)/s.Segment_()/" "$@"`

**Comment by zenhack** [comment]
This is a special case of #46; we still need to settle on a systematic way of avoiding name collisions.

I think concretely what changed is we went from generated types embedding capnp.Struct to having their underlying type *be* capnp.Struct (really StructKind, but...) in #283, which meant that all methods had to be defined explicitly. Previously, we just got these two from embedding `Struct`, so when the code generator generated a getter for a field called `Message`, it would just override those methods.

I think I'm with @lthibault about not changing this at least as a one-off; I probably have a large number of call sites that would be broken by this myself.

My inclination is to close this as a duplicate of #46, and just deal with the general case.

**Comment by mologie** [comment]
Sorry for the duplicate, I indeed missed the more general ticket! This also let me find `$Go.name()`, which seems to be helpful for some collisions even if it generates a bit of clutter.

**Comment by lthibault** [comment]
>Sorry for the duplicate

No worries!  I'm glad you opened the issue 😃 

>This also let me find $Go.name(), which seems to be helpful for some collisions even if it generates a bit of clutter.

Excellent!  By the way, please feel free to [ping us on Matrix](https://matrix.to/#/#go-capnp:matrix.org) if you encounter any API edge-cases in the future.  Sometimes it's easier to find workarounds (or scope a PR) in real-time.

See you around 👋
