### ISSUE TITLE
TestPipelineCall fails

### ISSUE THREAD

**Issue by lthibault** [capnproto/go-capnproto2#420]
```
=== RUN   TestPipelineCall
Error:     server_test.go:272: GetNumber() #1 = 1; want 0
Error:     server_test.go:278: GetNumber() #2 = 0; want 1
```

This is new, isn't it? ☝️

_Originally posted by @lthibault in https://github.com/capnproto/go-capnproto2/issues/418#issuecomment-1375740560_

**Comment by zenhack** [comment]
Git bisect blames 78440438b3b237c045c0d1110a9072056b73c5c3
