### ISSUE TITLE
rpc: add function to obtain local server from a capnp.Client

### ISSUE THREAD

**Issue by zombiezen** [capnproto/go-capnproto2#51]
In order to enable some APIs, there should be a function that goes from `capnp.Client` to a local server.  This is similar to `CapabilityServerSet::getLocalServer` in the C++ API.  However, just returning the `*server.server` isn't sufficient because a) it is an unexported type and b) does not contain a direct reference to the value from the `_ServerToClient` function.  I propose that the `*server.server` type should grow an `interface{}` field that can be anything, but is prepopulated by the generated `_ServerToClient` function to the passed-in server value.

Rough implementation plan:
1. Export `server.server` type and change `server.New` to return `*server.Server`.  Slightly breaking, but since the primary caller is generated code and the return type still obeys the `capnp.Client` interface, I think it's okay.
2. Add a `Value interface{}` field to `*server.Server`.
3. Update capnpc-go to populate `Server.Value` inside `_ServerToClient` functions.
4. Add a new interface to the capnp package (and make the appropriate clients implement it):

```
// ClientPromiser is an optional interface that a Client can implement if it can later resolve to another client.
type ClientPromiser interface {
  // ClientPromise returns a channel that is closed when the client is resolved.
  // The returned channel will be nil if this client is a real client, not a promise.
  ClientPromise() <- chan struct{}

  // ResolvedClient returns the resolved client, or nil if the client has not been resolved or the client is not a promise.
  ResolvedClient() capnp.Client
}

// ResolveClient waits until a client is fully resolved and returns it.
func ResolveClient(c capnp.Client) capnp.Client
```
1. Add a new function to server package:

```
// Resolve waits until a client is fully resolved, determines whether it is a Server, and if so, returns its Value field.  Otherwise, it returns nil.
func Resolve(c capnp.Client) interface{}
```

There's some hand-wavy details here, since either `Resolve` may need to cut through refcounts, but I think this is what I'd like to see happen.

/cc @zenhack for thoughts, since you're using the rpc package.

**Comment by zenhack** [comment]
Seems sensible enough to me, though I haven't found myself wanting this yet, so I can't say I have a lot of insight on what it should look like. Seems non-intrustive in any case.

**Comment by zombiezen** [comment]
Addressed in v3
