### ISSUE TITLE
pogs: fixed unions are hard to understand

### ISSUE THREAD

**Issue by abraithwaite** [capnproto/go-capnproto2#53]
Not sure if this is a bug in the code or docs, but I found an issue with pogs deserialization.

I made up an example of all the passing / failing cases here (each commit has different cases):

https://github.com/abraithwaite/pogs_example/commits/master

Specifically, when including an embedded struct which is represented by a union in capnproto, the docs say to use the "which=" tag to specify the capnp object to use.  This doesn't work for me.  Looking at the code, it appears that codepath exists still on HEAD:

https://github.com/zombiezen/go-capnproto2/blob/e255c9f719103c5329bc65aac0adcf12137b7424/pogs/fields.go#L174-L223

What's the expected behavior?  I'm happy to submit a patch.

I think the issue might actually be somewhere here:

https://github.com/zombiezen/go-capnproto2/blob/e255c9f719103c5329bc65aac0adcf12137b7424/pogs/fields.go#L30-L46

**Comment by zombiezen** [comment]
The docs can probably be made clearer, but I don't understand your example.  There's no union in that repo's schema AFAICT.

**Comment by abraithwaite** [comment]
![duh](http://i.imgur.com/iWKad22.jpg)

My bad.  I'll try this with an actual union type.  I don't think we have a union type come to think of it.

**Comment by abraithwaite** [comment]
Alright, I found what caused me to go off and try and reproduce this issue.

{code}
error: pogs: extract @0xe66193ff15e52403: can't extract User into main.User: has union field but no Which field
{code}

Is there any particular reason why it's required to have a `Which` field for deserialization?  If we have a field which is one of the unions, it seems reasonable to try and unpack that type, and throw an error if it's a different type instead of failing outright.

Should I open another issue and close this one?

**Comment by zombiezen** [comment]
So the way pogs expects this to be written right now is:

```go
type User struct {
  Which struct{} `capnp:",which=phone"`
  Phone Phone
  Id int64
  Name string
}
```

It's a bit clunky, but I'm trying to make it symmetric with serialization, which wouldn't be able to tell what value to put in the union.  I could relax this for deserialization, I suppose.  It has been a while since I've reasoned through this, and there are subtle edge cases.

**Comment by abraithwaite** [comment]
Maybe we should take this conversation elsewhere, but why wouldn't serialization be able to tell what to put in the Union, if only one of two fields is present?  I can understand if both are present it's ambiguous and then you need a determinant.

Also: it's unclear if named unions or multiple unions are supported.  We don't have any of these at the moment, but I'm willing to update the docs around these to be more accurate to the current implementation.

**Comment by zombiezen** [comment]
Sorry for delay, I was on vacation.  There are probably restrictions that can be relaxed, I just attempted to start off restrictive and loosen them over time.
