### ISSUE TITLE
rpc: allow specifying memory allocation strategy.

### ISSUE THREAD

**Issue by zenhack** [capnproto/go-capnproto2#60]
Background: the other day @justincormack wrote to the capnproto mailing list about his [memfd][1] package, which includes an implementation of the Arena interface required by go-capnproto2. I took a quick and dirty [whack][2] at implementing rpc.Transport on top of this, so it could actually be used for rpc, but for this to work we'd need to make sure the allocations all happen using memfds, and I don't see a way to get the rpc package to do that.

Unless I'm missing something, it would be nice to add a ConnOption that allows specifying a strategy or such. Maybe just taking a function that returns a new Arena.

Thoughts?

[1]: https://github.com/justincormack/go-memfd
[2]: https://github.com/zenhack/capnp-memrpc-go

**Comment by justincormack** [comment]
There was another thing that came up when doing this which was that `Message.Marshal()` always does append() on the message header and the segments. I could have supported this if `Marshal()` was delegated to the `Arena` as then I could have left space for the transport header at the beginning of the shared memory area, offsetting the segment. As it is I just ignored marshalling as it is not really needed but having it would make it easier to swap out different arena types potentially.

**Comment by zombiezen** [comment]
SGTM. Happy to accept a PR for this.  The approach sounds reasonable: there should be a custom `rpc.Transport` to avoid the call to `Marshal` (can be implemented using existing API) and there should be an `rpc.ConnOption` to specify the arena creation strategy for the `rpc.Conn` (needs a new API).

As for the message header copy, I'm not that familiar with this API, but you could skip the header if you have some other way of communicating segment boundaries.  Glancing at the arena implementation, you're only using one segment, right?

**Comment by justincormack** [comment]
Yes, it works fine without marshalling, there is one segment and the length is available anyway. It would only be useful if it was easier then to write more generic code.

**Comment by zombiezen** [comment]
Addressed in v3
