### ISSUE TITLE
rpc: rethink capnp.Client type

### ISSUE THREAD

**Issue by zombiezen** [capnproto/go-capnproto2#69]
I suspect this might be a backward compatible change, but I have growing concerns that capnp.Client is not quite the right abstraction.

* The use of finalizers seems like a hack at best.  There's no real safe way to call `Close()` on a received capability.  I haven't seen any issues for this, but I see that as a byproduct of the package's immaturity.  Ideally, at the end of a server request handler, all capabilities are released -- unless they are specifically asked to be retained.  Promoting ref-counting as a first-class concept would help.
* The current way of keeping track of resolved capabilities creates garbage.  Basically, they just proxy through to a new client type, but there's never really any way to clean the original one away, and it pushes this atomic proxying complexity to almost every implementation of a `Client`.
* Besides this, identifying what type of capability you have becomes complicated with proxies (#51 and #2).

I don't have concrete plans yet, but I'd like to have a tracking issue to point people towards.

**Comment by zenhack** [comment]
Can you elaborate on "There's no real safe way to call Close() on a received capability."?

**Comment by zombiezen** [comment]
If you call `Close()` right now, you aren't guaranteed that the RPC system isn't holding onto the same capability elsewhere.  I forget exactly where this comes up, but it would definitely be an issue if I were to try to fix #2.
