### ISSUE TITLE
Reduce allocations in streaming decoder

### ISSUE THREAD

**Issue by tj** [capnproto/go-capnproto2#79]
First of all this is awesome! Thanks a lot for the package.

I haven't looked heavily yet but the [msgp](https://github.com/tinylib/msgp) package seems to decode roughly ~70% faster given the same structure, which seems a little odd since one goal of capnproto is to reduce the allocations (and msgp has to construct everything).

I was thinking maybe splitting the framing out of the decoder so that Unmarshal can be used, allowing the user to decide whether or not it's safe to reference the memory. My main use-case for analytical type stuff where you just want to iterate and grab a field or two in-place.

Any thoughts? Maybe I missed an API in there, but it looked like the framing was built directly into the decoder.

IIRC msgp allows you to unmarshal against an existing byte slice (or allocs if necessary), I think it makes use of that pretty heavily internally which might be why it's quicker in this case. 

cheers

**Comment by zombiezen** [comment]
Do you have a Go-style benchmark where you can show the issue?  This library doesn't have nearly enough.
