### ISSUE TITLE
capnp: MultiSegment creates many small segments

### ISSUE THREAD

**Issue by zombiezen** [capnproto/go-capnproto2#99]
As a consequence of dea891aaf17, MultiSegment creates many single-digit word segments for small messages.  While the new algorithm does work better as the message grows, the first few segments ought to just grow to 1K.

/cc @recht

**Comment by recht** [comment]
Yes, there should be a minimum segment size, if that's what you're saying. I'm still using my own implementation which just doubles the size (at least) when the segment needs to be expanded, with a minimum size of 4k. However, that's implemented as a single segment due to #97.

**Comment by zombiezen** [comment]
Yup, I was mostly opening this issue in case folks were `go get`ing from master and ran into the issue so that I could point them to something.  It's fixed and released in 2.17.
